module.exports.descriptors = [
    // 'Forest',
    // 'Ancient',
    // 'Petrified',
    // 'Roaring',
    // 'Cascade',
    // 'Tumbling',
    // 'Silent',
    // 'Redwood',
    // 'Bullfrog',
    // 'Maple',
    // 'Misty',
    // 'Elk',
    // 'Grizzly',
    // 'Ocean',
    // 'Sea',
    // 'Sky',
    // 'Dusty',
    // 'Diamond'

    "Goan",
    "Konkan",
    "Udupi",
    "Punjabi",
    "Hyderabadi",
    "Bombay",
    "Hyderabadi",
    "Muradabadi",
    "Bihari",
    "Royal",
    "Grand",
    "Little",
    "Big",
    "New",
    "Golden",
    "Tasty",
    "Spicy",
    "Cheesy",
    "Fat"
]



module.exports.places = [
    // 'Flats',
    // 'Village',
    // 'Canyon',
    // 'Pond',
    // 'Group Camp',
    // 'Horse Camp',
    // 'Ghost Town',
    // 'Camp',
    // 'Dispersed Camp',
    // 'Backcountry',
    // 'River',
    // 'Creek',
    // 'Creekside',
    // 'Bay',
    // 'Spring',
    // 'Bayshore',
    // 'Sands',
    // 'Mule Camp',
    // 'Hunting Camp',
    // 'Cliffs',
    // 'Hollow'

    "Kitchen",
    "House",
    "Point",
    "Corner",
    "Park",
    "Mahal",
    "Bhavan",
    "Vilas",
    "Bistro",
    "Junction",
    "Lounge",
    "Station",
    "Boat",
    "Street",
    "Bites",
    "Biryani",
    "Shawarma",
    "Rolls",
    "Dosa",
    "Grill",
    "Barbecue",
    "Curry"
]

module.exports.description=[
    // "Chinese, Japanese",
    // "American, Chinese, North Indian, Italian",
    // "Cafe, Italian, North Indian",
    // "Italian, Continental",
    // "North Indian",
    // "South Indian",
    // "Asian, Italian, North Indian",
    // "Italian",
    // "Mughlai, North Indian, BBQ",
    // "Salad, Continental, Healthy Food",
    // "North Indian, Chinese, Fast Food",
    // "Mexican, Italian, North Indian",
    // "Gujarati",
    // "North Indian, Italian, Fast Food",
    // "Gujarati, North Indian, Chinese",
    // "North Indian, Italian, Mexican",
    // "North Indian, Chinese, Continental",
    // "Mexican, North Indian, Chinese, Italian, Asian, Beverages",
    // "Gujarati, Rajasthani",
    // "Cafe, North Indian",
    // "Modern Indian, North Indian, Parsi",
    // "Chinese, Asian, Seafood",
    // "Mughlai, North Indian, Chinese, BBQ, Biryani",
    // "Continental, Chinese, Thai, Mexican, Healthy Food, Beverages",
    // "South Indian, Desserts, Beverages",
    // "Asian, Continental, North Indian",
    // "North Indian, Continental",
    // "Pizza, Fast Food",
    // "North Indian, Mughlai, Seafood, Biryani",
    // "Pizza, Italian, Continental",
    // "Cafe, Italian",
    // "North Indian, Continental, Desserts",
    // "North Indian, Healthy Food",
    // "European, Continental",
    // "North Indian, Italian, Continental",
    // "Cafe, Italian, Continental, Fast Food, Beverages",
    // "Continental, Asian, North Indian",
    // "North Indian, Fast Food",
    // "North Indian, Mexican, Asian, Italian, Beverages",
    // "North Indian, Italian, Beverages",
    // "North Indian, Italian, Asian",
    // "Mexican, Italian",
    // "Mediterranean, North Indian, Desserts",
    // "North Indian, Mughlai, Biryani",
    // "Continental, North Indian, Fast Food",
    // "North Indian, Beverages",
    // "Continental, Italian, North Indian",
    // "North Indian, Chinese, Mexican, Ice Cream",
    // "North Indian, Fast Food, Mughlai",
    // "North Indian, Continental, Italian",
    // "North Indian, Continental, Chinese",
    // "North Indian, Italian, Chinese",
    // "Mexican, North Indian, Italian",
    // "Italian, Mexican",
    // "North Indian, Continental, Fast Food, BBQ, Italian, Modern Indian",
    // "Chinese, North Indian, Continental",
    // "Italian, North Indian",
    // "North Indian, Continental, Italian, Mexican",
    // "North Indian, Mughlai, Chinese, Fast Food",
    // "North Indian, Chinese, Italian",
    // "Japanese, Asian, Chinese",
    // "Healthy Food, North Indian",
    // "North Indian, Gujarati, Italian, Desserts",
    // "Healthy Food, Beverages, Italian",
    // "North Indian, Fast Food, Chinese, Sandwich, Beverages",
    // "Italian, Mexican, North Indian",
    // "Continental, Mexican",
    // "Fast Food, Street Food, South Indian",
    // "Mexican, Mediterranean, Thai, Korean",
    // "Desserts, Ice Cream, Fast Food",
    // "Street Food, Desserts, Gujarati, Fast Food",
    // "Fast Food",
    // "Lebanese",
    // "South Indian, Fast Food",
    // "Fast Food, Bakery",
    // "Burger, Fast Food",
    // "Street Food"

    "“I love Indian food – it’s my favourite cuisine. I love the mixture of spices and the subtle flavours. It’s really erotic",
  "“When I venture out to eat, I like to go to places with food that I don’t know how to make. So my favorites are Japanese and Indian. Indian food has so much layering of flavor, and the dishes go together so harmoniously.” – Gwyneth Paltrow",
  "“Culture and tradition have to change little by little. So ‘new’ means a little twist, a marriage of Japanese technique with French ingredients. My technique. Indian food, Korean food",
  "“I remember flying with Air India to New York quite a few years ago now and I love Indian food, so the fact that I had a curry on board was fantastic.” – Phil Collins",
  "“I was far too embarrassed to share the experience of Indian food at school. As a kid, you’re desperate to fit in, to assimilate in some way, and everything about me stood out.” – Sanjeev Bhaskar",
  "“When I was younger I was fat. I was never conscious of it and was content with who I was because I was so loved. My mother never told me to lose weight and my father doted on me, but my agent told me. I tried, but I loved Indian food too much.” – Archie Panjabi",
  "“I do love Italian food. Any kind of pasta or pizza. My new pig out food is Indian food. I eat Indian food like three times a week. It’s so good.” – Jennifer Love Hewitt",
  "“My wife has a line of fine Indian foods, that’s kind of a very successful business. It’s an interesting way to see life.” – Guy Lawson",
  "“So often these days eating Indian food passes for spirituality. I don’t meditate, I don’t pray, but I eat two samosas every day.” – Dan Bern",
  "“My mind says one thing, but my body says another. Thanks a lot, Indian food and beer.” ~ Demetri Martin",
  "“As I grew up, I always refused to cook Indian food very vehemently, and to this day, I don’t cook chapatis at home. I’d always say, ‘Why do I have to do it? Why don’t the men do it?’” – Gurinder Chadha",
  "“I think there is a real misconception about Indian food being super spicy. And I know that’s because when you go into an Indian restaurant, it is pretty spicy. But it doesn’t have to be. In fact, my husband can’t handle a lot of heat. I’ve had to temper my cooking so that he can eat with me.” – Aarti Sequeira",
  "“All foreign food is doomed to be consumed in India not so much by Indians as by a voracious Indian sensibility, which demands infinite versions of Indian food, and is unmoved by difference.” – Amit Chaudhuri",
  "“I like a lot of food. I like Taiwanese food, of course. I like baguettes, especially the ones that my dad buys. Vancouver has a lot of variety, with pizza, hot dogs, Italian, Indian, seafood – a great combination of cultures.” – Godfrey Gao",
  "“Indian food has been huge in the UK forever and ever, but that’s because it has a historical rooting. America, I think is really ripe for it. There’s been so much interest in Indian culture.” – Aarti Sequeira",
  "“My mother was born in Burma, but my grandfather on her side was Indian-Spanish. So I have this quite exotic mix, which is reflected in my earliest memories, in our Wiltshire country kitchen, of gran, and aunts, cooking spicy stewy, casseroley curries, a version of Indian food with a Burmese twist.” – Jamie Cullum",
  "“Indian food is a luxury on tour.” – Mahesh Bhupathi",
  "“As for restaurants, one of our favorites is the Silk Road next door to the Tibetan Choijin Lama Museum. It’s a very exotic setting. The western food there is pretty good. We also liked the Hazara Restaurant for its Indian food, and the Mongolian Barbecue restaurant. All are downtown.” – Ruth Lor Malloy",
  "“I’m encouraged because you pick up any food magazine and there’s two or three recipes involving Indian spices.” – Aarti Sequeira",
  "“I cannot starve myself. I’m a foodie! I make fabulous pastas, Indian food, parathas and club sandwiches!” – Preity Zinta",
  "“I eat only simple Indian home food – sabzi, roti, dal, chawal, ghee. There are so many benefits of having ghee. My grandmother is 84 and she is still fit and looks beautiful.” – Kareena Kapoor Khan",
  "“The only time to eat diet food is while you’re waiting for the steak to cook.” – Julia Child",
  "“You’re the Chutney to my Samosa.” – Anonymous",
  "“Eat Indian food and curry on.” – Anonymous",
  "“Sitting down to a meal with an Indian family is different from sitting down to a meal with a British family.” – Roland Joffe",
  "“The food we ate was Indian, and both my mother and father were very deep into the ancient philosophy of India, so it could well have been an Indian household.” – Amar Bose",
  "“One can hardly be Indian and not know that almost every accent, which hand you eat your food with, has some deeper symbolic truth, reality.” – Anish Kapoor",
  "“Indian cinema gives you everything that western cinema doesn’t. It’s masaledar and spicy. If you like Indian food, I think you’ll love Indian movies.” – Shahid Kapoor",
  "“I am not a stickler for Indian food, but by the third day or so I start looking for something familiar to eat. I have travelled a lot, and I always try out local food.” – Shaan",
  "“Indian food, not really for rednecks.” – Anonymous",
  "“People always think of Chinese food as the go-to ethnic food when everything else is closed during the holidays, but Indian is a nice alternative. Plus – Indians? Thanksgiving? Kinda makes sense.” – Erin Gibson",
  "“You just feel a little odd when you don’t get your kind of food. Fortunately, there are Indian restaurants all over the world.” – Virat Kohli",
  "“I like to cook Indian food when I can. I find the process of creating a home-cooked meal to be unwinding.” – Archie Panjabi",
  "“Don’t go and cook Indian food if you never cooked Indian food, you know?” – Wolfgang Puck",
  "“Indian food is like classical music raga- it takes time to build up to a crescendo.” – Shobhaa De"
]

